@apiUrl= http://localhost:8080/abrigos

### GET /abrigos
GET {{apiUrl}}/

### GET /abrigos/:id
@id:1 = 1
GET {{apiUrl}}/{{id:1}}

### POST /abrigos
POST {{apiUrl}}/
Content-Type: application/json

{
    "nome": "Abrigo AnimalMundi"
}

### PATCH /abrigos/:id [Todos os campos opc]
@id:2=5
PATCH {{apiUrl}}/{{id:2}}
Content-Type: application/json

{
    "nome": "Centro Auquemia"
}

### DELETE /abrigos/:id
@id:3=6
DELETE {{apiUrl}}/{{id:3}}