@apiUrl= http://localhost:8080/pets

### GET /pets
GET {{apiUrl}}/

### GET /pets/:id
@id:1 = 1
GET {{apiUrl}}/{{id:1}}

### POST /pets
POST {{apiUrl}}/
Content-Type: application/json

{
    "nome": "Tchucão",
    "descricao": "Brincalão e bagunceiro",
    "idade": "5 meses", 
    "endereco": "Rua latido, 123 - Rio de Janeiro",
    "imagem": "https://picsum.photos/200/300",
}

### PATCH /pets/:id [Todos os campos opc]
@id:2=1
PATCH {{apiUrl}}/{{id:2}}
Content-Type: application/json

{
    "nome": "Tchucão",
    "descricao": "Brincalão e bagunceiro",
    "idade": "5 meses", 
    "endereco": "Rua latido, 123 - Rio de Janeiro",
    "imagem": "https://picsum.photos/200/300",
}

### DELETE /pets/:id
@id:3=1
DELETE {{apiUrl}}/{{id:3}}